import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design tokens (preserved exactly)
        "on-primary-fixed-variant": "#554500",
        "primary": "#715c00",
        "outline-variant": "#d0c6ab",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#231b00",
        "inverse-on-surface": "#f3f0ef",
        "inverse-surface": "#313030",
        "surface": "#fcf9f8",
        "on-tertiary-container": "#b81c22",
        "on-tertiary-fixed-variant": "#930011",
        "surface-variant": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "surface-tint": "#715c00",
        "tertiary-fixed-dim": "#ffb3ad",
        "secondary-fixed-dim": "#ffb875",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-surface-variant": "#4d4632",
        "surface-dim": "#dcd9d9",
        "on-primary": "#ffffff",
        "tertiary-container": "#ffccc7",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#ffdad6",
        "on-surface": "#1c1b1b",
        "primary-fixed": "#ffe17a",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f0eded",
        "on-background": "#1c1b1b",
        "secondary": "#8c4f00",
        "on-primary-container": "#705c00",
        "on-tertiary-fixed": "#410003",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#ecc300",
        "secondary-fixed": "#ffdcc0",
        "primary-container": "#ffd41d",
        "on-secondary-fixed-variant": "#6b3b00",
        "on-secondary-container": "#6b3b00",
        "inverse-primary": "#ecc300",
        "surface-container-high": "#eae7e7",
        "tertiary": "#b91d23",
        "background": "#fcf9f8",
        "outline": "#7f7760",
        "secondary-container": "#fda13f",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed": "#2d1600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        gutter: "24px",
        lg: "48px",
        base: "8px",
        md: "24px",
        sm: "12px",
        xl: "80px",
        "container-max": "1280px",
      },
      fontFamily: {
        "display-xl": ["var(--font-poppins)", "Poppins", "sans-serif"],
        "headline-md": ["var(--font-poppins)", "Poppins", "sans-serif"],
        "headline-sm": ["var(--font-poppins)", "Poppins", "sans-serif"],
        "headline-lg": ["var(--font-poppins)", "Poppins", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
